### ISSUE TITLE
Tips from a learner to a learner

### ISSUE THREAD

**Issue by HornyakBence** [theIYD/implementations-java#1]
For gcd:
Dont just print the result at the end. Show the user all of the steps. 

And the above is true for all the calc type methods. 
Try to make main as short as possible. One line should be good. :smiley: 
Also read **Clean Code: A Handbook of Agile Software Craftsmanship**. It's kind of a basic book. 

Check out [this subreddit](https://www.reddit.com/r/dailyprogrammer/) it also has some pretty  good tasks.
Also take a look at JUnit tests and documenting. 
Project lombok can be handy later. 
After you wrote some tests its a good idea to use gradle here as well. For automating all the tests after u changed the code base and also has a fancy test html option if turn it on (google that). 
Try not to write separate main method for every example. Instead of that try to create a "box" that have all the stuff that you want to demonstrate and just call all the methods from one main method. 

Good luck learning.

**Comment by smartagent47** [comment]
Thank you for the suggestion.
